DROP TABLE IF EXISTS user;
--DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  heb_name TEXT,
  mail_address TEXT UNIQUE NOT NULL,
  phone_number TEXT NOT NULL,
  car_number TEXT NOT NULL,
  qualification INTEGER
);

--CREATE TABLE post (
--  id INTEGER PRIMARY KEY AUTOINCREMENT,
--  author_id INTEGER NOT NULL,
--  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--  title TEXT NOT NULL,
--  body TEXT NOT NULL,
--  FOREIGN KEY (author_id) REFERENCES user (id)
--);